- hosts: terraform-ansible
  tasks:
  - name: instalando o python3, virtualenv
    apt:
      pkg:
      - python3
      - python3-django
      - virtualenv
      update_cache: yes
    become: yes
  - name: instalando dependências com pip (Django e Django rest)
    pip:
      virtualenv: /home/ubuntu/tcc/venv
      name:
        - django
        - djangorestframework
  - name: "verificando se o projeto já existe"
    stat:
      path: home/ubuntu/tcc/setup/settings.py
    register: projeto
  - name: iniciando o projeto
    shell: './home/ubuntu/tcc/venv/bin/activate; django-admin startproject setup /home/ubuntu/tcc/'
    when: not projeto.stat.exists
  - name: alterando hosts do settings
    lineinfile:
      path: /home/ubuntu/tcc/setup/settings.py
      regexp: 'ALLOWED_HOSTS'
      line: 'ALLOWED_HOSTS = ["*"]'
      backrefs: yes
