- hosts: [terraform-ansible]
  tasks:
  - name: criando o arquivo
    copy:
      dest: /home/ubuntu/index.html
      content: <h1> anna esta aprendendo a usar o ansible junto com o terraform </h1> <h2>e se sentindo adoravel!</h2>
  - name: criando o servidor
    shell: "nohup busybox httpd -f -p 8080 &"